spring:
  application:
    name: menu-service

  data:
    mongodb:
      uri: mongodb://mongodb:27017/posdb

  server:
    port: 8080

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.data.mongodb.core: DEBUG
    org.mongodb.driver: DEBUG
    org.springframework.validation: DEBUG
    com.restaurant.pos.menuservice: DEBUG
    feign: DEBUG